baseURL = 'https://pablogarcor.com/'
title = 'pablogarcor Site'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false

[languages]
  [languages.en]
    contentDir = 'content/en'
    locale = 'en-US'
    label = 'English'
    weight = 1

  [languages.es]
    contentDir = 'content/es'
    locale = 'es-ES'
    label = 'Español'
    weight = 2

[permalinks]
  blog = "/:slug/"
